# learning Python

In [1]:
1+1

2

In [2]:
print(1+1)

2


In [3]:
1.0+1

2.0

In [4]:
1/2.0

0.5

In [5]:
2*2

4

In [8]:
2*2

4

In [9]:
4**4

256

In [11]:
4%2 #shares reminder

0

In [20]:
5 % 6

5

In [21]:
num = 12
name = 'Sam'

In [22]:
'My number is {} and my name is {}'.format(num,name)

'My number is 12 and my name is Sam'

In [23]:
'My number is {one} and my name is {two}, {one}'.format(one = num,two =name)

'My number is 12 and my name is Sam, 12'

In [25]:
name[:2]

'Sa'

In [26]:
name[1:]

'am'

In [27]:
[1,2,3]

[1, 2, 3]

In [28]:
my_list = ['a', 'b', 'c']

In [29]:
my_list.append('d')

In [35]:
my_list

['a', 'b', 'c', 'd', 'e']

In [34]:
my_list.insert(4,'e')

In [37]:
my_list[0] = 'New'

In [38]:
my_list

['New', 'b', 'c', 'd', 'e']

In [39]:
my_list[0] = my_list

In [40]:
my_list

[[...], 'b', 'c', 'd', 'e']

In [41]:
#Dictionaries

In [42]:
d = {'key1': 'value', 'key2': 123}

In [45]:
d['key2']

123

In [47]:
d = {'k1': [1,2,3]}

In [50]:
d['k1']

[1, 2, 3]

In [51]:
d['k1'][2]

3

In [55]:
if (3<2):
    print(' one is less than  two')
elif (3==3):
    print('second option')
else:
    print('last')
        

second option


In [56]:
seq = [1,2,3,4,5]

In [57]:
for item in seq:
    print(item)

1
2
3
4
5


In [70]:
i = 1
while i < 5:
    print('i is: {}'.format(i))
    i = i+1

i is: 1
i is: 2
i is: 3
i is: 4


In [76]:
range(10)
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [78]:
x = [1,2,3,4]
out = []

for num in x:
    out.append(num**2)
    
print(out)

[1, 4, 9, 16]


In [87]:
def my_func(param1='Default Name'):
    print('hello ' + param1)

In [89]:
my_func('Akbar')

hello Akbar


In [98]:
def sqr(num):
    """
    This function expects the number and squares the number
    """
    return num**num

In [100]:
my_output = sqr(5)
my_output

3125

In [103]:
list(range(5,25))

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

In [104]:
seq= [1,2,3,4,5]

In [108]:
def times2(var):
    return var*2

In [110]:
list(map(times2, seq))

[2, 4, 6, 8, 10]

In [111]:
list(map(lambda num: num*3, seq))

[3, 6, 9, 12, 15]

In [114]:
list(filter(lambda num: num%2==0, seq))

[2, 4]

In [115]:
my_name = 'My name is Akbar'

In [128]:
my_name.split('i')

['My name ', 's Akbar']

In [129]:
chk_tweet = 'Go Sports! #Sports'

In [130]:
chk_tweet.split('#')

['Go Sports! ', 'Sports']

In [131]:
chk_tweet.split('#')[1]

'Sports'

In [132]:
'x' in [1,2,3]

False

In [133]:
'x' in ['x', 'y','z']

True

# Numpy Array 

In [134]:
my_list = [1,2,3]

In [135]:
my_list

[1, 2, 3]

In [136]:
import numpy as np

In [137]:
np.array(my_list)

array([1, 2, 3])

In [138]:
my_arr = np.array(my_list)

In [139]:
my_arr

array([1, 2, 3])

In [143]:
my_mdarray = [[1,2,3],[4,5,6],[7,8,9]]

In [144]:
my_mdarray

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [145]:
np.array(my_mdarray)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# range function of numpy

In [146]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [149]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

# Generate digit vector or matrix

In [150]:
np.zeros(3)

array([0., 0., 0.])

In [151]:
np.ones(3)

array([1., 1., 1.])

In [153]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [157]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# Evenly spaced points

In [160]:
np.linspace(1,10,25) # Returns 25 evenly spaced points between 1 and 10

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

# Generate two dimension array with zero and one - generally used with Linear Algebra

In [161]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Generate random variables

In [163]:
np.random.rand(5)

array([0.11912323, 0.80036048, 0.18196581, 0.92778655, 0.6237508 ])

In [164]:
np.random.rand(3,3)

array([[0.18842929, 0.8286226 , 0.38425162],
       [0.43285946, 0.37987398, 0.10462903],
       [0.06853715, 0.71460408, 0.02141059]])

In [165]:
np.random.randn(5)

array([ 0.8824193 , -0.78407184,  0.9874751 ,  1.02914262, -0.48121591])

In [166]:
np.random.randn(5,5)

array([[ 0.03310216,  0.47393076, -0.11820849, -0.32204718, -1.12007749],
       [ 1.12585052, -0.43484614,  0.32315515, -1.58639032,  1.70903779],
       [-2.31499886,  0.08265158, -0.05318696, -0.25274501,  0.73882032],
       [-0.64152438, -0.23739748,  0.44080579,  0.8376971 , -0.71084044],
       [ 0.97922772, -1.10877592, -1.49297364,  0.37239615,  0.1332571 ]])

In [168]:
np.random.randint(0,5,10)

array([3, 0, 4, 0, 3, 2, 4, 2, 2, 4])

In [172]:
arr = np.arange(25)

In [173]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [174]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [180]:
npRandom = np.random.randint(1,25,10)

In [181]:
npRandom

array([ 2, 14,  6, 14,  1,  7, 22, 12,  5, 10])

In [176]:
arr.max() # max value in the array

24

In [178]:
arr.min() # min value in the array

0

In [182]:
npRandom.max() # max value in the array

22

In [183]:
npRandom.min() # min value in the array

1

In [187]:
npRandom.argmax() # returns the index of max value

6

In [188]:
npRandom.argmin() # returns the index of min value

4

In [190]:
npRandom.shape # returns shapes of the vector

(10,)

In [192]:
npRandom.dtype # returns the datatype of the array

dtype('int64')

In [206]:
npRandom

array([ 2, 14,  6, 14,  1,  7, 22, 12,  5, 10])

In [207]:
npRandom[7:]

array([12,  5, 10])

In [210]:
arr_new = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [213]:
arr_new

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [214]:
arr_new[0]

array([ 5, 10, 15])

In [218]:
arr_new[1][1]

25

In [220]:
arr_new[2][1]

40

In [226]:
arr_new[:1,2:]

array([[15]])

In [227]:
npRandom

array([ 2, 14,  6, 14,  1,  7, 22, 12,  5, 10])

In [229]:
npRandom[npRandom>10]

array([14, 14, 22, 12])

In [230]:
arr_2d = np.arange(50).reshape(5,10)

In [231]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [232]:
arr_2d[1,1]

11

In [250]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [251]:
npRandom

array([ 2, 14,  6, 14,  1,  7, 22, 12,  5, 10])

In [257]:
npRandom ** 5

array([     32,  537824,    7776,  537824,       1,   16807, 5153632,
        248832,    3125,  100000])