In [8]:
import numpy as np

#### Create an array of 10 zeros 

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [13]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [92]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [93]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [21]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [22]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [29]:
np.random.rand(1)

array([0.54921836])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [31]:
np.random.randn(25)

array([-1.13288726, -0.47040148,  1.34626919, -1.80899052,  0.39978275,
        1.01740814,  1.75236254,  0.77753068,  0.13410481, -0.86826283,
       -1.34559994, -0.19422481,  1.30996215,  0.70142578, -0.57237163,
        1.77698491, -0.62179042,  0.94539578,  1.68596782, -2.33958034,
        0.91013264, -2.92123903,  0.13203617,  0.20819893,  1.64347972])

#### Create the matrix:

In [46]:
np.arange(0.01,1.01,.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [50]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [51]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [58]:
mat[2:,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [71]:
mat[3:4,4:5]

array([[20]])

In [86]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [87]:
mat[4]

array([21, 22, 23, 24, 25])

In [89]:
mat.sum()

325

In [90]:
mat.std()

7.211102550927978

In [91]:
sum(mat)

array([55, 60, 65, 70, 75])

## Starting with Pandas

#Series

In [95]:
import pandas as pd

In [98]:
labels = [ 'a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10, 'b':20, 'c':30}

In [101]:
pd.Series(data = my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [102]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [103]:
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [104]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [105]:
ser1 = pd.Series([1,2,3,4],['First', 'Second', 'Third','Forth'])

In [106]:
ser1

First     1
Second    2
Third     3
Forth     4
dtype: int64

In [107]:
ser1['First']

1

In [108]:
ser1 + ser1

First     2
Second    4
Third     6
Forth     8
dtype: int64

In [109]:
ser1 *5

First      5
Second    10
Third     15
Forth     20
dtype: int64

# DataFrame

In [111]:
np.random.seed(101) #- same random number

In [117]:
df = pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [118]:
df

W         X         Y         Z
A -1.467514 -0.494095 -0.162535  0.485809
B  0.392489  0.221491 -0.855196  1.541990
C  0.666319 -0.538235 -0.568581  1.407338
D  0.641806 -0.905100 -0.391157  1.028293
E -1.972605 -0.866885  0.720788 -1.223082

In [119]:
df['W']

A   -1.467514
B    0.392489
C    0.666319
D    0.641806
E   -1.972605
Name: W, dtype: float64

In [120]:
type(df)

pandas.core.frame.DataFrame

In [121]:
type(df['W'])

pandas.core.series.Series

In [124]:
df[['W','Z']]

W         Z
A -1.467514  0.485809
B  0.392489  1.541990
C  0.666319  1.407338
D  0.641806  1.028293
E -1.972605 -1.223082

In [125]:
df['New'] = df['X'] + df['Y']

In [126]:
df

W         X         Y         Z       New
A -1.467514 -0.494095 -0.162535  0.485809 -0.656630
B  0.392489  0.221491 -0.855196  1.541990 -0.633705
C  0.666319 -0.538235 -0.568581  1.407338 -1.106816
D  0.641806 -0.905100 -0.391157  1.028293 -1.296257
E -1.972605 -0.866885  0.720788 -1.223082 -0.146097

In [127]:
df['New']

A   -0.656630
B   -0.633705
C   -1.106816
D   -1.296257
E   -0.146097
Name: New, dtype: float64

In [129]:
df.drop('New',axis=1)

W         X         Y         Z
A -1.467514 -0.494095 -0.162535  0.485809
B  0.392489  0.221491 -0.855196  1.541990
C  0.666319 -0.538235 -0.568581  1.407338
D  0.641806 -0.905100 -0.391157  1.028293
E -1.972605 -0.866885  0.720788 -1.223082

In [130]:
df

W         X         Y         Z       New
A -1.467514 -0.494095 -0.162535  0.485809 -0.656630
B  0.392489  0.221491 -0.855196  1.541990 -0.633705
C  0.666319 -0.538235 -0.568581  1.407338 -1.106816
D  0.641806 -0.905100 -0.391157  1.028293 -1.296257
E -1.972605 -0.866885  0.720788 -1.223082 -0.146097

In [132]:
df.drop('New',axis=1,inplace=True)

In [133]:
df

W         X         Y         Z
A -1.467514 -0.494095 -0.162535  0.485809
B  0.392489  0.221491 -0.855196  1.541990
C  0.666319 -0.538235 -0.568581  1.407338
D  0.641806 -0.905100 -0.391157  1.028293
E -1.972605 -0.866885  0.720788 -1.223082

In [134]:
df.drop('E')

W         X         Y         Z
A -1.467514 -0.494095 -0.162535  0.485809
B  0.392489  0.221491 -0.855196  1.541990
C  0.666319 -0.538235 -0.568581  1.407338
D  0.641806 -0.905100 -0.391157  1.028293

In [135]:
df.shape

(5, 4)

In [138]:
df.loc['A','Y']

-0.1625347347726149

In [139]:
df.iloc[2,0]

0.6663193209198146

In [140]:
df.loc[['A','C'], ['X','Z']]

X         Z
A -0.494095  0.485809
C -0.538235  1.407338

In [143]:
df[df>.3]

W   X         Y         Z
A       NaN NaN       NaN  0.485809
B  0.392489 NaN       NaN  1.541990
C  0.666319 NaN       NaN  1.407338
D  0.641806 NaN       NaN  1.028293
E       NaN NaN  0.720788       NaN

In [146]:
df[df['W']>.3]

W         X         Y         Z
B  0.392489  0.221491 -0.855196  1.541990
C  0.666319 -0.538235 -0.568581  1.407338
D  0.641806 -0.905100 -0.391157  1.028293

In [148]:
df[df['W']>.3]['X']

B    0.221491
C   -0.538235
D   -0.905100
Name: X, dtype: float64

In [149]:
df

W         X         Y         Z
A -1.467514 -0.494095 -0.162535  0.485809
B  0.392489  0.221491 -0.855196  1.541990
C  0.666319 -0.538235 -0.568581  1.407338
D  0.641806 -0.905100 -0.391157  1.028293
E -1.972605 -0.866885  0.720788 -1.223082

In [153]:
df[(df['W']>0) & (df['Z']>0)]

W         X         Y         Z
B  0.392489  0.221491 -0.855196  1.541990
C  0.666319 -0.538235 -0.568581  1.407338
D  0.641806 -0.905100 -0.391157  1.028293

In [154]:
df.reset_index()

index         W         X         Y         Z
0     A -1.467514 -0.494095 -0.162535  0.485809
1     B  0.392489  0.221491 -0.855196  1.541990
2     C  0.666319 -0.538235 -0.568581  1.407338
3     D  0.641806 -0.905100 -0.391157  1.028293
4     E -1.972605 -0.866885  0.720788 -1.223082

In [155]:
df

W         X         Y         Z
A -1.467514 -0.494095 -0.162535  0.485809
B  0.392489  0.221491 -0.855196  1.541990
C  0.666319 -0.538235 -0.568581  1.407338
D  0.641806 -0.905100 -0.391157  1.028293
E -1.972605 -0.866885  0.720788 -1.223082

In [156]:
States = 'CA NY, WY OR CO'.split()

In [157]:
States

['CA', 'NY,', 'WY', 'OR', 'CO']

In [159]:
df['States'] = States

In [160]:
df

W         X         Y         Z States
A -1.467514 -0.494095 -0.162535  0.485809     CA
B  0.392489  0.221491 -0.855196  1.541990    NY,
C  0.666319 -0.538235 -0.568581  1.407338     WY
D  0.641806 -0.905100 -0.391157  1.028293     OR
E -1.972605 -0.866885  0.720788 -1.223082     CO

In [161]:
df.set_index('States')

W         X         Y         Z
States                                        
CA     -1.467514 -0.494095 -0.162535  0.485809
NY,     0.392489  0.221491 -0.855196  1.541990
WY      0.666319 -0.538235 -0.568581  1.407338
OR      0.641806 -0.905100 -0.391157  1.028293
CO     -1.972605 -0.866885  0.720788 -1.223082

In [162]:
df

W         X         Y         Z States
A -1.467514 -0.494095 -0.162535  0.485809     CA
B  0.392489  0.221491 -0.855196  1.541990    NY,
C  0.666319 -0.538235 -0.568581  1.407338     WY
D  0.641806 -0.905100 -0.391157  1.028293     OR
E -1.972605 -0.866885  0.720788 -1.223082     CO

# Multi Index - Hirarchy system

In [163]:
# Index Levels
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1,2,3,1,2,3]
heir_index = list(zip(outside, inside))
heir_index = pd.MultiIndex.from_tuples(heir_index)

In [164]:
####

In [165]:
d = {'A': [1,2,np.nan], 'B':[5,np.nan,np.nan], 'C':[1,2,3]}

In [166]:
d

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [167]:
df = pd.DataFrame(d)

In [168]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [169]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [170]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [171]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [172]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [173]:
df.fillna('Fill Value')

A           B  C
0           1           5  1
1           2  Fill Value  2
2  Fill Value  Fill Value  3

In [174]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [175]:
df['A'].fillna(df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# Group By

In [178]:
data = {'Company':['COOG', 'COOG', 'MSFT','MSFT','FB','FB'],
'Person':['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
    'Sales': [200,120,340,124,243,350]}

In [179]:
data

{'Company': ['COOG', 'COOG', 'MSFT', 'MSFT', 'FB', 'FB'],
 'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
 'Sales': [200, 120, 340, 124, 243, 350]}

In [180]:
df = pd.DataFrame(data)

In [181]:
df

Company   Person  Sales
0    COOG      Sam    200
1    COOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [183]:
byComp = df.groupby('Company')

In [187]:
byComp.sum()

Sales
Company       
COOG       320
FB         593
MSFT       464

In [191]:
df.groupby('Company').sum()

Sales
Company       
COOG       320
FB         593
MSFT       464

In [193]:
df.groupby('Company').describe().transpose()

Company            COOG          FB        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   160.000000  296.500000  232.000000
      std     56.568542   75.660426  152.735065
      min    120.000000  243.000000  124.000000
      25%    140.000000  269.750000  178.000000
      50%    160.000000  296.500000  232.000000
      75%    180.000000  323.250000  286.000000
      max    200.000000  350.000000  340.000000

In [197]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [195]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [196]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [199]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [202]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})  

pd.merge(left,right,how='inner',on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [203]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [204]:
pd.merge(left,right,how='inner',on=['key1','key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [205]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [207]:
df['col2'].unique()

array([444, 555, 666])

In [208]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [209]:
def times2(x):
    return x*2

In [210]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [216]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [217]:
df.sort_values('col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

# Data input and output

In [218]:
pwd

'/Users/akbaralishaikh/Documents/GIT/Data-Science/Python'

In [222]:
my_example = pd.read_csv('example.csv')

In [227]:
pd.DataFrame(my_example)

Satisfaction  Loyalty
0              4    -1.33
1              6    -0.28
2              5    -0.99
3              7    -0.29
4              4     1.06
5              1    -1.66
6             10    -0.97
7              8    -0.32
8              8     1.02
9              8     0.68
10            10    -0.34
11             5     0.39
12             5    -1.69
13             2     0.67
14             7     0.27
15             9     1.36
16             8     1.38
17             7     1.36
18             7    -0.34
19             9     0.67
20            10     1.18
21             3    -1.69
22             4     1.04
23             3    -0.96
24             6     1.03
25             9    -0.99
26            10     0.37
27             9     0.03
28             3    -1.36
29             5     0.73

In [229]:
my_example.to_csv('my_output.csv', index=False)

In [230]:
pd.read_csv('my_output.csv')

Satisfaction  Loyalty
0              4    -1.33
1              6    -0.28
2              5    -0.99
3              7    -0.29
4              4     1.06
5              1    -1.66
6             10    -0.97
7              8    -0.32
8              8     1.02
9              8     0.68
10            10    -0.34
11             5     0.39
12             5    -1.69
13             2     0.67
14             7     0.27
15             9     1.36
16             8     1.38
17             7     1.36
18             7    -0.34
19             9     0.67
20            10     1.18
21             3    -1.69
22             4     1.04
23             3    -0.96
24             6     1.03
25             9    -0.99
26            10     0.37
27             9     0.03
28             3    -1.36
29             5     0.73

In [234]:
df = pd.read_excel('Excel_Sample.xlsx', sheetname='Sheet1')

In [235]:
pd.DataFrame(df)
df.to_excel('Excel_Sample2.xlsx', sheet_name='NewSheet1')

In [250]:
df = pd.read_html('https://www.fdic.gov/bank/individual/failed/banklist.html')

In [251]:
type(df)

list

In [253]:
df = pd.DataFrame(df[0])

In [254]:
df.head()

Bank Name         City  ST   CERT  \
0                Washington Federal Bank for Savings      Chicago  IL  30570   
1    The Farmers and Merchants State Bank of Argonia      Argonia  KS  17719   
2                                Fayette County Bank   Saint Elmo  IL   1802   
3  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...    Milwaukee  WI  30003   
4                                     First NBC Bank  New Orleans  LA  58302   

                 Acquiring Institution       Closing Date       Updated Date  
0                   Royal Savings Bank  December 15, 2017   February 1, 2019  
1                          Conway Bank   October 13, 2017  February 21, 2018  
2            United Fidelity Bank, fsb       May 26, 2017   January 29, 2019  
3  First-Citizens Bank & Trust Company        May 5, 2017     March 22, 2018  
4                         Whitney Bank     April 28, 2017   January 29, 2019